name: Gitleaks

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  gitleaks:
    name: Secret Scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GITLEAKS_LICENSE only required for organization accounts, not personal accounts
          # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
